---
- hosts: all
  become: yes
  tasks:
    - block:
        - parted: device=/dev/sda unit=GiB
          register: sdb_info
        - debug:
            msg: '{{ sdb_info.disk.size }}GB'
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Distribution
    debug:
      msg: "{{ ansible_distribution }}"
  - name: Distribution version
    debug:
      msg: "{{ ansible_distribution_version}}"
  - hosts: all
  become: yes
  vars:
    nic: all
  tasks:
    - name: MAC Address
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
    - name: network interfaces
      debug:
        msg: "{{ ansible_interfaces }}"
